### ISSUE TITLE
Feature: Mob Kills, Command/Gamestages Rewards.

### ISSUE THREAD

**Issue by darkshadow543** [LatvianModder/FTBQuests#10]
I am currently developing a pack called(Temp Name) Age of Magic Revived.  I am using Game Stages to section off parts of the game.  One of the things I would like to do is give the player the gamestage once they have completed the hunting task. I understand if this is difficult, but it would be nice to have this.

**Comment by CrankySupertoon01** [comment]
Use a command reward similar to how MSB3 did

**Comment by LatvianModder** [comment]
Command rewards can be done by giving players Script item with NBT tag "command"
