### ISSUE TITLE
Quest text is hard to see

### ISSUE THREAD

**Issue by CrankySupertoon01** [LatvianModder/FTBQuests#11]
My first one is that this text should be another color. Unless im missing something gray is very hard to see.
![image](https://user-images.githubusercontent.com/26016256/44742275-743d6b80-aacd-11e8-8c0b-920d1bef311c.png)

**Comment by CrankySupertoon01** [comment]
1 Still applys, 2 and 3 are fixed

**Comment by LatvianModder** [comment]
Oh, yeah, this text was designed for the white background, imma change it
