### ISSUE TITLE
Disable Random Reward tooltip when out of editing mode or with advanced tooltips disabled

### ISSUE THREAD

**Issue by aaronhowser1** [LatvianModder/FTBQuests#110]
It kind of ruins the surprise of not knowing what you can get if you have a huge list of stuff that has a chance of dropping. Maybe limit it to only be shown when you're either in editing mode or you have advanced tooltips enabled?

**Comment by LatvianModder** [comment]
There is a setting for disabling tooltip, in Reward Table
