### ISSUE TITLE
Add more then 14 quest chapters

### ISSUE THREAD

**Issue by CrankySupertoon01** [LatvianModder/FTBQuests#12]
Is there a reason that there is a hardcoded limit. This is the only thing blocking me atm with making my modpack. If not mind making it 20 or until it doesnt fit anymore (dont know the magic number)

**Comment by CrankySupertoon01** [comment]
Still think it is a hardcoded limit because NBTExplorer did nothing

**Comment by CrankySupertoon01** [comment]
If the issue was if the quests can fit into those tabs maybe add a slider that you can slide, but who plays on the minimal size

**Comment by LatvianModder** [comment]
Why do you need more than 14 chapters? 14 is all that fits in a GUI at smallest size, can't go above that, unless I add some kind of scrolling mechanism which would be kinda annoying

**Comment by CrankySupertoon01** [comment]
I trying to make a modpack where each mod has a different chapter. Could you try to implament a scrolling meckanism. If you cant could you do two rows. Or if not can you remove the hardcoded limit so my nbt editor will work

**Comment by LatvianModder** [comment]
I will add scrolling mechanic
