### ISSUE TITLE
Add Questbook Item

### ISSUE THREAD

**Issue by EngineerXL** [LatvianModder/FTBQuests#2]
I suggest to make a Questbook item and smaller interface, because this window is too HUGE [I lost my mouse icon on it]

**Comment by CommanderTvis** [comment]
I agree. Else I'll probably make an addon to implement it 🐹

**Comment by EngineerXL** [comment]
Also is there (will there) be language files for quests? Eg. en_US = "Craft a furnace"; ru_RU = "Сделай печь"
