### ISSUE TITLE
Just read the desription i dont know how to word this

### ISSUE THREAD

**Issue by CrankySupertoon01** [LatvianModder/FTBQuests#21]
Maybe as a option for quest rewards you can get points. This doesn't replace the items but maybe you can get points for finishing quests and then maybe you can add a store button for rewards.

In other words you dont get spammy chance cubes / loot crates but instead can get points which can be used towards an item you really want.

I guess this is duable with Content Tweaker and another quest chapter but meh.

I still think its a cool idea

**Comment by CrankySupertoon01** [comment]
For goodness sake i think it would fit in FTB Quests but if you dont think so, maybe an entire other mod called FTB Store that can integrate with Quests kinda like an expansion addon. Idk just giving random ideas

**Comment by LatvianModder** [comment]
We actually had the same exact idea lol. It will be in FTB Utilities, however, as money & shop system.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/126
