### ISSUE TITLE
Mob Kills Task

### ISSUE THREAD

**Issue by CrankySupertoon01** [LatvianModder/FTBQuests#23]
When i was redoing the agrarian skies 2 map with this mod with my new project it came to me that you cannot set a task as a mob kill. This isnt that important for me beacuse i used mob drops but maybe it would be in the final task to kill the ender dragon. Or some of those twilight forest mobs

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBQuests/issues/56
