### ISSUE TITLE
Text box doesn't enlarge at all sometimes, while other text boxes do even when they don't have that much text.

### ISSUE THREAD

**Issue by clootas** [LatvianModder/FTBQuests#39]
Example:
![ftb bug](https://user-images.githubusercontent.com/32606683/45984363-c3c07a00-c02e-11e8-85b9-0cdbf82f58a2.jpg)

**Comment by LatvianModder** [comment]
Yeah they currently only change size based on buttons and other non-text widgets. Since text can expand and wrap it wouldn't know when to stop and you don't want it to expand sideways infinitely. I might add some kind of min/max size though
