### ISSUE TITLE
My Suggestion 

### ISSUE THREAD

**Issue by Jasondia16** [LatvianModder/FTBQuests#40]
Add Ore Dictionary and More Reward Choices like better Questing ie, Checkbox, Etc

Thanks ^^

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBQuests/issues/36

**Comment by CrankySupertoon01** [comment]
I hate to reopen this but i think @Jasondia16 meant Reward Choices as in Choice Rewards. #36 doesnt involve that

**Comment by CrankySupertoon01** [comment]
Better Questing can already do that with its XOR logic so if you want use that for now. I wouldnt expect him the use that soon

**Comment by Jasondia16** [comment]
k
