### ISSUE TITLE
Crash on attempt to AddReward

### ISSUE THREAD

**Issue by Nachtflame** [LatvianModder/FTBQuests#43]
Forge 2765
FTBLib 5.3.0.54
FTBQuests 1.2.0.54
FTBUtils 5.3.0.52

When editing Quests, clicking on the 'Add Reward' button causes hard crash (back to launcher)

[crash-2018-10-04_10.12.28-client.txt](https://github.com/LatvianModder/FTBQuests/files/2447378/crash-2018-10-04_10.12.28-client.txt)

[crash-2018-10-04_10.08.33-client.txt](https://github.com/LatvianModder/FTBQuests/files/2447380/crash-2018-10-04_10.08.33-client.txt)

**Comment by LatvianModder** [comment]
For now you can just use Ctrl+Click

**Comment by Nachtflame** [comment]
Thanks!
