### ISSUE TITLE
Quest items auto-detection

### ISSUE THREAD

**Issue by fguillod** [LatvianModder/FTBQuests#52]
Playing the brand new FTB Sky Adventure 1.0.0-1.12.2, I realised I was missing something relatively useful from other quest mods like Better Questing, which is the auto-detection of quest completion.

For a lot of quests in the modpack, I had to create a block that was really useful for the progression, like the sieve. So I opened the quest book, saw that I need to craft a sieve, crafted it, placed it immediately to use it, opened my quest book a little while later and **realized that the quest was not completed**. I then had to break the sieve, complete the quest and place it again. And this for a lot of blocks, actually.

So, could you please implement the auto-detection of quest completion / quest items ?

**Comment by Blizzor** [comment]
would be great, if the auto-detection could be added. Don't want to use another Quest Mod.
