### ISSUE TITLE
Include a message when somebody isn't in a FTB team

### ISSUE THREAD

**Issue by TheFlash787** [LatvianModder/FTBQuests#53]
Hey! We have this issue where if somebody hasn't created a team, they are unable to hand in any quests (Since we aren't using Team Islands). This causes much confusion as everybody is new to this system.

**Suggestion: ** Include a message that is shown on the questing GUI when somebody tries to open it, that they must have created a FTB team before continuing. 

Just a small tweak! Thank you very much.

**Comment by generrosity** [comment]
Is it possible to allow people to complete quests while they are not part of a team? Is there a specific requirement for being in a team, or is it just a nice structure for storing?

**Comment by LatvianModder** [comment]
The requirement is like that because of how FTBLib works. I plan to rewrite it at some point, that would allow "single player / self teams". But its mostly due to how data is stored and synced

**Comment by LatvianModder** [comment]
Good? ![](https://ss.latmod.com/pc/2018-10-23_01.33.19.png)

**Comment by generrosity** [comment]
Niiiice.

**Comment by TheFlash787** [comment]
Yes, that's fantastic. I assume this will be in the next version. Thank you.
