### ISSUE TITLE
Editing Reward Chests - Loot crates

### ISSUE THREAD

**Issue by MokahTGS** [LatvianModder/FTBQuests#54]
Has this system been implemented yet?  I can see the loot crate items in JEI, and reward them via quests but they don't do anything when opened.  I couldn't see any configs or jsons that define them in any way.  Am I missing something or has this feature not been implemented fully yet?

**Comment by LatvianModder** [comment]
If you want to simply use a vanilla loot table, you can change the loot table ID in File Settings of quests to, for example, `minecraft:chests/abandoned_mineshaft`.
If you want more advanced control over items, you need to use CraftTweaker and LootTweaker to edit loot tables. You can check out FTB Sky Adventures on how it does it.
