### ISSUE TITLE
[Suggestion] Tasks - Crafting Item Vs Getting Item

### ISSUE THREAD

**Issue by MokahTGS** [LatvianModder/FTBQuests#55]
If you could add a task capability for detecting crafting an item vs just getting an item that would go a long way to adding complexity to quest design.

**Comment by LatvianModder** [comment]
How about this instead? https://github.com/LatvianModder/FTBQuests/issues/52 Supporting crafting in minecraft isn't reliable. I think advancements check for item in inventory too
