### ISSUE TITLE
Ticking Tile Entity crash 

### ISSUE THREAD

**Issue by BonaireDreams** [LatvianModder/FTBQuests#68]
Pyramid Reborn 3.0.0 pack
Every few days my client crashes when trying to join my server. A full server reboot usually fixes it. Odd thing is the server does a reboot every night.  Appears to be FTB Quests causing it.

Description: Ticking block entity
java.lang.NullPointerException: Ticking block entity
	at com.feed_the_beast.ftbquests.tile.TileProgressDetector.getTeam(TileProgressDetector.java:122)

[crash-2018-10-25_21.57.32-client.txt](https://github.com/LatvianModder/FTBQuests/files/2517798/crash-2018-10-25_21.57.32-client.txt)

**Comment by CrankySupertoon01** [comment]
Not Fixed
[crash-2018-11-08_15.58.28-client.txt](https://github.com/LatvianModder/FTBQuests/files/2563595/crash-2018-11-08_15.58.28-client.txt)
