### ISSUE TITLE
Can't do any quest

### ISSUE THREAD

**Issue by K4kugen** [LatvianModder/FTBQuests#69]
Hello,
I just started a little modded server with SkyAdventure (last version)
I get necessary for my first quest : 16 oak wood planks, but i can't reward my quest
The submit button is completly disable (the "[0%]" is drak grey), i can't submit, and the edit mode don't resolve that, the "complet instantly" don't work

I hope you can help me
Cordially,
A French player who try to speak english

**Comment by Aiidoneus** [comment]
You HAVE to start a FTB Team.

**Comment by K4kugen** [comment]
Oh ok my bad
You resolve my problem of quest & map,j thanks for it
Sorry to inconvenience you 
Thanks again for the help
