### ISSUE TITLE
Quest Dependencies are bugged.

### ISSUE THREAD

**Issue by CrankySupertoon01** [LatvianModder/FTBQuests#7]
They dont work, and the game doesnt crash,

**Comment by CrankySupertoon01** [comment]
![image](https://user-images.githubusercontent.com/26016256/44491124-3f916600-a62e-11e8-8028-cb7c2f8ba22e.png)

**Comment by CrankySupertoon01** [comment]
Also suggestion. Dont make me type the Dependency.

How to fix that

Add a line dragging tool or a drag down / search box instead of a type the quest name box

**Comment by LatvianModder** [comment]
You can do that already, its just a bit hidden feature right now - Ctrl + click on a quest to select it, then rightclick on child quest and add dependency. You can also move selected quests with Ctrl + Arrow
