### ISSUE TITLE
Crash [java.lang.StackOverflowError]

### ISSUE THREAD

**Issue by R-ZERO** [LatvianModder/FTBQuests#70]
https://paste.dimdev.org/ukadoleyam.mccrash

java.lang.StackOverflowError
    at com.feed_the_beast.ftbquests.quest.Quest.getVisibility(Quest.java:570)... crash

**Comment by LatvianModder** [comment]
Uh oh, looping dependencies. Can't fix this one, right now. See https://github.com/LatvianModder/FTBQuests/issues/44
