### ISSUE TITLE
[Suggestion] More control over repeatable quests

### ISSUE THREAD

**Issue by chillar85** [LatvianModder/FTBQuests#71]
More control over repeatable quests like

- how often is a  quest repeatable before it is completed for good

- timer til it is repeatable again (every x ticks, hourly, daily, ...)

- staggering cost after each repeat  first x item, second x+10 items, ...)

**Comment by LatvianModder** [comment]
One of those things is here already https://github.com/LatvianModder/FTBQuests/issues/17

**Comment by LatvianModder** [comment]
Can you open first two as separate issues?
