### ISSUE TITLE
Quests not resetting

### ISSUE THREAD

**Issue by Master-Jynx** [LatvianModder/FTBQuests#75]
I play on several servers run buy FTB Complex Gaming, which is trying to host a
FTB Sky Adventures server.
I was one of the first to log on to it and try it, when I triggered a bug, thats hard to describe
so i will explain what i did that led up to it.
It was very early game and i completed 3 quests (got the crook) , when I fell off the island and died,
I "lost" the quest book and not yet being familiar with the game, I deletes the island and recreated,
which triggered a bug that was corrupting recreated islands (not related to this mod).
When it was fixed my quests were not reset, and no way could be found to do so.
With the help of the server Admin, it was found that by leaving my team (even if i was the only member)
my quests would be reset, But afterwards, the quest system stopped working, it doesn't see the 16x oak planks in my inventory for the first quest.
the tool tip for the left button says 0%  completed and is unclickable
the reward button have a red X and are unclickable.
All quest are uncompleteable.

**Comment by LatvianModder** [comment]
Update / Wait for update and reopen if this still happens
