### ISSUE TITLE
[Suggestion] Text suggestions

### ISSUE THREAD

**Issue by SynexWolf** [LatvianModder/FTBQuests#77]
Ability to be able to use a custom colour text for the "text" section of the quest, possibly by following minecraft's formatting codes.

Edit: It would also be nice if there was a bigger gap between texts.
![image](https://user-images.githubusercontent.com/25542341/47964429-c5497d00-e085-11e8-9cc4-1ecd388519f7.png)

**Comment by LatvianModder** [comment]
Done in https://github.com/LatvianModder/FTBQuests/commit/503494a8917f0ead7e91ac006b6ef1608b787537

**Comment by kreezxil** [comment]
Is this in 1.2.1.62 version?
