### ISSUE TITLE
Really not a issue but a important suggestion

### ISSUE THREAD

**Issue by CrankySupertoon01** [LatvianModder/FTBQuests#8]
I would for once make a description on the curse page that explains the mod power, because i was in 3 discord servers and about 50 people were asking why this guy wanted a screen addon for a quest pack, and im like yeah they are not reading the book but judging the cover.

Was this mod really made for FTB Pyramid, or was it made for a new FTB Pack...

Also i have heard FTB Achievements but JSONable, and im like ...

**Comment by LatvianModder** [comment]
This mod is made for everyone, but it has some features that were made specifically for the modpack. However, I made sure those features can be used in other modpacks. For example, Screen blocks can be used for automation by any player, so can be quest chests, you just have to add recipes for them with crafttweaker. WIP description here, but I will finish it after I finish making the base of mod (its far from done as it currently is on curseforge) https://minecraft.curseforge.com/projects/ftb-quests/pages/for-players
