### ISSUE TITLE
Crash Report 1.12.2 Im Not Able To Load The Mod

### ISSUE THREAD

**Issue by mrM6** [LatvianModder/FTBQuests#81]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/feed_the_beast/ftblib/events/CustomSidebarButtonTextEvent

**Comment by LatvianModder** [comment]
Update or downgrade FTBLib
