### ISSUE TITLE
Reset Progress button should reset progress for that specific quest, with another button to reset progress of all quests

### ISSUE THREAD

**Issue by aaronhowser1** [LatvianModder/FTBQuests#88]

**Comment by LatvianModder** [comment]
You mean like clicking on chapter to reset it's progress? :P

**Comment by aaronhowser1** [comment]
As it is now, when you right click a quest and click Reset Progress it resets all your progress in all your quests. I was suggesting that that only resets that quest mainly, with the "reset all" thing somewhere else, like the chapter icon yeah.
