### ISSUE TITLE
removing dependencies visual bug

### ISSUE THREAD

**Issue by Sunekaer** [LatvianModder/FTBQuests#89]
After removing dependencies from a quest the visual line between them is still there until relog.
only tested on server

**Comment by LatvianModder** [comment]
Build .69 should fix it

**Comment by Sunekaer** [comment]
Just tested in .70 issue still there
Visual bug on servers fixed by relog
Crash in SP https://paste.feed-the-beast.com/view/1b56c232

**Comment by Sunekaer** [comment]
Game crashed again when trying to enter the world again
https://paste.feed-the-beast.com/view/d5313ef6
