### ISSUE TITLE
Null Pointer while Initializing Game

### ISSUE THREAD

**Issue by MeinKraft** [LatvianModder/FTBQuests#93]
FTBQuests 1.3.2.73
Forge 2775

playing FTB Sky Adventures.  Game crashes during loading mods with Crash Log https://pastebin.com/uqaZNUSd

It mentions CraftTweaker. I tried 4.1.12 and 4.1.13 of CraftTweaker and crash still happens

**Comment by avidgamer5918** [comment]
I had the same problem. downgrading the version to 1.3.2.72 fixed the crash for me

**Comment by LatvianModder** [comment]
Update to 74
