### ISSUE TITLE
Quest resets upon rebooting the server

### ISSUE THREAD

**Issue by captcookie** [LatvianModder/FTBQuests#96]
Forge 2775
FTB Quest 73
FTB Lib 60

All other FTB mods up to date. Reported on discord, mod author is aware.

**Comment by captcookie** [comment]
Tried version 74 same result. Gave latest log to mod author.

**Comment by LatvianModder** [comment]
This feels like an FTBLib bug, because claimed chunks stopped saving at the same time, and I havent touched those in months

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/891
