### ISSUE TITLE
Quests not working

### ISSUE THREAD

**Issue by SakuraBliss** [LatvianModder/FTBQuests#97]
So i just started a world and automatically i did most of the things required for the quests but none of them were completed, they weren't even progressed slightly, stuck at zero, my quest for getting 4 oak is stil not completed and it really annoys me. I had everything I need in my inventory too but it still doesn't complete when i try to turn it in. It doesn't even let me turn the items in actually.
![image](https://user-images.githubusercontent.com/45319788/48973120-5a48f180-f006-11e8-9b6d-a5cee488c235.png)

**Comment by captcookie** [comment]
sometimes you have to toggle nbt ignore. happened to me too.

**Comment by captcookie** [comment]
example enhanced armaments will give me a variations of stone pick axe. So the nbt will be off or whatever.

**Comment by SakuraBliss** [comment]
> 
> 
> example enhanced armaments will give me a variations of stone pick axe. So the nbt will be off or whatever.

question, how would you do that? Sorry im just rlly stupid.

**Comment by LatvianModder** [comment]
Did you complete Wallet first? You can't turn in quests without completing all previous ones

**Comment by SakuraBliss** [comment]
that must be it, sorry i never used and ftb modpack before and most of the mods I havent even seen before.
